services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Glossary2\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  JWeiland\Glossary2\EventListener\AddPaginatorEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Glossary2\Event\PostProcessFluidVariablesEvent

  JWeiland\Glossary2\EventListener\AddGlossaryEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Glossary2\Event\PostProcessFluidVariablesEvent
        after: JWeiland\Glossary2\EventListener\AddPaginatorEventListener

  JWeiland\Glossary2\Helper\CharsetHelper:
    public: true

  JWeiland\Glossary2\Service\GlossaryService:
    public: true

  # Called by makeInstance out of TypoScript
  JWeiland\Glossary2\PageTitleProvider\Glossary2PageTitleProvider:
    public: true
